### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by gaspo53** [amarjeetanandsingh/jps_stat#3]
Hi! First of all, thanks for this tool, it's really helpful!
This issue happens all the time, after running it for a while:

cut: /proc/36627/statm: No such file or directory
./jpsstat.sh: line 93: / 1024 : syntax error: operand expected (error token is "/ 1024 ")

Redhat RHEL 7.

**Comment by rakeshts** [comment]
I am facing this error too. Is there a solution available ?

**Comment by ymzong** [comment]
@gaspo53 @rakeshts I believe the cause of your issue is this:
between Line 70 (where `curr_pid_name` is populated) and Line 93 (where the `pid` is used to grab runtime metrics), the process has died. Or in short, TOCTTOU.

There should be graceful error handling on Line 93, where if a process can no longer be found, it should continue silently.

**Comment by gaspo53** [comment]
Thank you Amar for give us the tool!
